web:
  image: tutum/hello-world
  expose:
   - "80"

prom_haproxy_histogram:
  build: .
  ports:
    - "9080:9080"
    - "514:514"

prometheus:
  image: prom/prometheus:0.18.0
  ports:
   - "9090:9090"
  volumes:
   - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  links:
   - prom_haproxy_histogram

lb:
  image: tutum/haproxy
  links:
   - web
   - prom_haproxy_histogram
  ports:
   - "80:80"
  environment:
   - BACKEND_PORT=80
   - BALANCE=roundrobin
   - RSYSLOG_DESTINATION=prom_haproxy_histogram
